version: "2"
run:
  allow-parallel-runners: true
linters:
  settings:
    staticcheck:
      dot-import-whitelist: # allow dot imports for the following packages
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
formatters:
  enable:
    - gofmt
    - goimports
