version: "2"
run:
  allow-parallel-runners: true
linters:
  settings:
    staticcheck:
      dot-import-whitelist: # allow dot imports for the following packages
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - embeddedstructfieldcheck
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - godoclint
    - godox
    - gosec
    - interfacebloat
    - ireturn
    - maintidx
    - mnd
    - nestif
    - nilerr
    - nilnil
    - noctx
    - noinlineerr
    - paralleltest
    - revive
    - tagliatelle
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - linters:
          - lll

          # kubebuiler generates code that triggers godot, so we disable it for the api/ directory.
          - godot

          # modernize rejects omitempty on nested structs, but we admit them due to kubebuiler conventions.
          # cf. https://github.com/golang/go/issues/76649
          - modernize
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*

      # exclude staticcheck SA1019 for Result.Requeue.
      - linters:
          - staticcheck
        text: "SA1019: .*\\.Requeue is deprecated: Use `RequeueAfter` instead."

formatters:
  enable:
    - gofmt
    - goimports
