// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ceph/ceph.go
//
// Generated by this command:
//
//	mockgen -source=internal/ceph/ceph.go -destination=internal/ceph/ceph_mock.go -package=ceph
//

// Package ceph is a generated GoMock package.
package ceph

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCephCmd is a mock of CephCmd interface.
type MockCephCmd struct {
	ctrl     *gomock.Controller
	recorder *MockCephCmdMockRecorder
	isgomock struct{}
}

// MockCephCmdMockRecorder is the mock recorder for MockCephCmd.
type MockCephCmdMockRecorder struct {
	mock *MockCephCmd
}

// NewMockCephCmd creates a new mock instance.
func NewMockCephCmd(ctrl *gomock.Controller) *MockCephCmd {
	mock := &MockCephCmd{ctrl: ctrl}
	mock.recorder = &MockCephCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCephCmd) EXPECT() *MockCephCmdMockRecorder {
	return m.recorder
}

// CephRBDTaskAddTrashRemove mocks base method.
func (m *MockCephCmd) CephRBDTaskAddTrashRemove(pool, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CephRBDTaskAddTrashRemove", pool, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// CephRBDTaskAddTrashRemove indicates an expected call of CephRBDTaskAddTrashRemove.
func (mr *MockCephCmdMockRecorder) CephRBDTaskAddTrashRemove(pool, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CephRBDTaskAddTrashRemove", reflect.TypeOf((*MockCephCmd)(nil).CephRBDTaskAddTrashRemove), pool, image)
}

// RBDClone mocks base method.
func (m *MockCephCmd) RBDClone(pool, srcImage, srcSnap, dstImage, features string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDClone", pool, srcImage, srcSnap, dstImage, features)
	ret0, _ := ret[0].(error)
	return ret0
}

// RBDClone indicates an expected call of RBDClone.
func (mr *MockCephCmdMockRecorder) RBDClone(pool, srcImage, srcSnap, dstImage, features any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDClone", reflect.TypeOf((*MockCephCmd)(nil).RBDClone), pool, srcImage, srcSnap, dstImage, features)
}

// RBDInfo mocks base method.
func (m *MockCephCmd) RBDInfo(pool, image string) (*RBDImageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDInfo", pool, image)
	ret0, _ := ret[0].(*RBDImageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RBDInfo indicates an expected call of RBDInfo.
func (mr *MockCephCmdMockRecorder) RBDInfo(pool, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDInfo", reflect.TypeOf((*MockCephCmd)(nil).RBDInfo), pool, image)
}

// RBDLockAdd mocks base method.
func (m *MockCephCmd) RBDLockAdd(pool, image, lockID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDLockAdd", pool, image, lockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RBDLockAdd indicates an expected call of RBDLockAdd.
func (mr *MockCephCmdMockRecorder) RBDLockAdd(pool, image, lockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDLockAdd", reflect.TypeOf((*MockCephCmd)(nil).RBDLockAdd), pool, image, lockID)
}

// RBDLockLs mocks base method.
func (m *MockCephCmd) RBDLockLs(pool, image string) ([]*RBDLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDLockLs", pool, image)
	ret0, _ := ret[0].([]*RBDLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RBDLockLs indicates an expected call of RBDLockLs.
func (mr *MockCephCmdMockRecorder) RBDLockLs(pool, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDLockLs", reflect.TypeOf((*MockCephCmd)(nil).RBDLockLs), pool, image)
}

// RBDLockRm mocks base method.
func (m *MockCephCmd) RBDLockRm(pool, image string, lock *RBDLock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDLockRm", pool, image, lock)
	ret0, _ := ret[0].(error)
	return ret0
}

// RBDLockRm indicates an expected call of RBDLockRm.
func (mr *MockCephCmdMockRecorder) RBDLockRm(pool, image, lock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDLockRm", reflect.TypeOf((*MockCephCmd)(nil).RBDLockRm), pool, image, lock)
}

// RBDLs mocks base method.
func (m *MockCephCmd) RBDLs(pool string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDLs", pool)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RBDLs indicates an expected call of RBDLs.
func (mr *MockCephCmdMockRecorder) RBDLs(pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDLs", reflect.TypeOf((*MockCephCmd)(nil).RBDLs), pool)
}

// RBDRm mocks base method.
func (m *MockCephCmd) RBDRm(pool, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDRm", pool, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// RBDRm indicates an expected call of RBDRm.
func (mr *MockCephCmdMockRecorder) RBDRm(pool, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDRm", reflect.TypeOf((*MockCephCmd)(nil).RBDRm), pool, image)
}

// RBDSnapCreate mocks base method.
func (m *MockCephCmd) RBDSnapCreate(pool, image, snap string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDSnapCreate", pool, image, snap)
	ret0, _ := ret[0].(error)
	return ret0
}

// RBDSnapCreate indicates an expected call of RBDSnapCreate.
func (mr *MockCephCmdMockRecorder) RBDSnapCreate(pool, image, snap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDSnapCreate", reflect.TypeOf((*MockCephCmd)(nil).RBDSnapCreate), pool, image, snap)
}

// RBDSnapLs mocks base method.
func (m *MockCephCmd) RBDSnapLs(pool, image string) ([]RBDSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDSnapLs", pool, image)
	ret0, _ := ret[0].([]RBDSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RBDSnapLs indicates an expected call of RBDSnapLs.
func (mr *MockCephCmdMockRecorder) RBDSnapLs(pool, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDSnapLs", reflect.TypeOf((*MockCephCmd)(nil).RBDSnapLs), pool, image)
}

// RBDSnapRm mocks base method.
func (m *MockCephCmd) RBDSnapRm(pool, image, snap string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDSnapRm", pool, image, snap)
	ret0, _ := ret[0].(error)
	return ret0
}

// RBDSnapRm indicates an expected call of RBDSnapRm.
func (mr *MockCephCmdMockRecorder) RBDSnapRm(pool, image, snap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDSnapRm", reflect.TypeOf((*MockCephCmd)(nil).RBDSnapRm), pool, image, snap)
}

// RBDTrashMv mocks base method.
func (m *MockCephCmd) RBDTrashMv(pool, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RBDTrashMv", pool, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// RBDTrashMv indicates an expected call of RBDTrashMv.
func (mr *MockCephCmdMockRecorder) RBDTrashMv(pool, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RBDTrashMv", reflect.TypeOf((*MockCephCmd)(nil).RBDTrashMv), pool, image)
}
