// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.2
// source: pkg/controller/proto/controller.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateOrUpdatePVCRequest is a request message for CreateOrUpdatePVC RPC.
type CreateOrUpdatePVCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pvc string `protobuf:"bytes,1,opt,name=pvc,proto3" json:"pvc,omitempty"`
}

func (x *CreateOrUpdatePVCRequest) Reset() {
	*x = CreateOrUpdatePVCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_proto_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdatePVCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdatePVCRequest) ProtoMessage() {}

func (x *CreateOrUpdatePVCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_proto_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdatePVCRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdatePVCRequest) Descriptor() ([]byte, []int) {
	return file_pkg_controller_proto_controller_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrUpdatePVCRequest) GetPvc() string {
	if x != nil {
		return x.Pvc
	}
	return ""
}

// CreateOrUpdatePVCResponse is a response message for CreateOrUpdatePVC RPC.
type CreateOrUpdatePVCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CreateOrUpdatePVCResponse) Reset() {
	*x = CreateOrUpdatePVCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_proto_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdatePVCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdatePVCResponse) ProtoMessage() {}

func (x *CreateOrUpdatePVCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_proto_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdatePVCResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdatePVCResponse) Descriptor() ([]byte, []int) {
	return file_pkg_controller_proto_controller_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrUpdatePVCResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// CreateOrUpdateMantleBackupRequest is a request message for CreateOrUpdateMantleBackup RPC.
type CreateOrUpdateMantleBackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MantleBackup string `protobuf:"bytes,1,opt,name=mantleBackup,proto3" json:"mantleBackup,omitempty"`
}

func (x *CreateOrUpdateMantleBackupRequest) Reset() {
	*x = CreateOrUpdateMantleBackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_proto_controller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateMantleBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateMantleBackupRequest) ProtoMessage() {}

func (x *CreateOrUpdateMantleBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_proto_controller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateMantleBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateMantleBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_controller_proto_controller_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrUpdateMantleBackupRequest) GetMantleBackup() string {
	if x != nil {
		return x.MantleBackup
	}
	return ""
}

// CreateOrUpdateMantleBackupResponse is a response message for CreateOrUpdateMantleBackup RPC.
type CreateOrUpdateMantleBackupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateMantleBackupResponse) Reset() {
	*x = CreateOrUpdateMantleBackupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_proto_controller_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateMantleBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateMantleBackupResponse) ProtoMessage() {}

func (x *CreateOrUpdateMantleBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_proto_controller_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateMantleBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateMantleBackupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_controller_proto_controller_proto_rawDescGZIP(), []int{3}
}

var File_pkg_controller_proto_controller_proto protoreflect.FileDescriptor

var file_pkg_controller_proto_controller_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c,
	0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x56, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x76,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x76, 0x63, 0x22, 0x2d, 0x0a, 0x19,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x56,
	0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x21, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e,
	0x74, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x22, 0x24, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xda, 0x01, 0x0a, 0x0d, 0x4d,
	0x61, 0x6e, 0x74, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x56,
	0x43, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x56, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x56, 0x43, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x12, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x79, 0x62, 0x6f, 0x7a, 0x75, 0x2d, 0x67, 0x6f, 0x2f,
	0x6d, 0x61, 0x6e, 0x74, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_controller_proto_controller_proto_rawDescOnce sync.Once
	file_pkg_controller_proto_controller_proto_rawDescData = file_pkg_controller_proto_controller_proto_rawDesc
)

func file_pkg_controller_proto_controller_proto_rawDescGZIP() []byte {
	file_pkg_controller_proto_controller_proto_rawDescOnce.Do(func() {
		file_pkg_controller_proto_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_controller_proto_controller_proto_rawDescData)
	})
	return file_pkg_controller_proto_controller_proto_rawDescData
}

var file_pkg_controller_proto_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_controller_proto_controller_proto_goTypes = []interface{}{
	(*CreateOrUpdatePVCRequest)(nil),           // 0: proto.CreateOrUpdatePVCRequest
	(*CreateOrUpdatePVCResponse)(nil),          // 1: proto.CreateOrUpdatePVCResponse
	(*CreateOrUpdateMantleBackupRequest)(nil),  // 2: proto.CreateOrUpdateMantleBackupRequest
	(*CreateOrUpdateMantleBackupResponse)(nil), // 3: proto.CreateOrUpdateMantleBackupResponse
}
var file_pkg_controller_proto_controller_proto_depIdxs = []int32{
	0, // 0: proto.MantleService.CreateOrUpdatePVC:input_type -> proto.CreateOrUpdatePVCRequest
	2, // 1: proto.MantleService.CreateOrUpdateMantleBackup:input_type -> proto.CreateOrUpdateMantleBackupRequest
	1, // 2: proto.MantleService.CreateOrUpdatePVC:output_type -> proto.CreateOrUpdatePVCResponse
	3, // 3: proto.MantleService.CreateOrUpdateMantleBackup:output_type -> proto.CreateOrUpdateMantleBackupResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_controller_proto_controller_proto_init() }
func file_pkg_controller_proto_controller_proto_init() {
	if File_pkg_controller_proto_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_controller_proto_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdatePVCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_proto_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdatePVCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_proto_controller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateMantleBackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_proto_controller_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateMantleBackupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_controller_proto_controller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_controller_proto_controller_proto_goTypes,
		DependencyIndexes: file_pkg_controller_proto_controller_proto_depIdxs,
		MessageInfos:      file_pkg_controller_proto_controller_proto_msgTypes,
	}.Build()
	File_pkg_controller_proto_controller_proto = out.File
	file_pkg_controller_proto_controller_proto_rawDesc = nil
	file_pkg_controller_proto_controller_proto_goTypes = nil
	file_pkg_controller_proto_controller_proto_depIdxs = nil
}
