{{- if eq .Values.controller.role "secondary" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mantle.fullname" . }}-replication
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.replicationService.type }}
  ports:
  - port: {{ .Values.replicationService.port }}
    targetPort: {{ .Values.replicationService.targetPort }}
    protocol: TCP
    name: replication
    {{- with .Values.replicationService.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    {{- include "mantle.selectorLabels" . | nindent 4 }}
{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mantle.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.webhook.service.port }}
    targetPort: {{ .Values.webhook.service.targetPort }}
    protocol: TCP
    name: webhook
  selector:
    {{- include "mantle.selectorLabels" . | nindent 4 }}
{{ end }}
{{ end }}
