name: "ceph custom export-diff release"
on:
  push:
    tags:
      - "ceph-export-diff-v*.*.*.*"
permissions:
  contents: write
  id-token: write
jobs:
  release:
    runs-on: mantle_large_runner_16core
    timeout-minutes: 240
    steps:
      - run: sudo apt-get update
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-go
        with:
          go-version-file: "go.mod"
          cache: false
          takumi-guard-bot-id: ${{ vars.TAKUMI_GUARD_BOT_ID }}
      - uses: ./.github/actions/set-up-kvm-for-e2e-tests
      - run: make -C ceph setup
      - run: make -C ceph build
      - run: |
          VERSION=${GITHUB_REF#refs/tags/}
          zip -j packages.zip ceph/packages/*.deb ceph/packages/COPYING*
          gh release create "${VERSION}" -t "Release ${VERSION}"
          gh release upload "${VERSION}" packages.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
