name: "e2e"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "LICENSE"
      - "NOTICE"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "LICENSE"
      - "NOTICE"
    branches:
      - "main"
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - 1.35.4
          - 1.34.4
    runs-on: "ubuntu-22.04"
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - run: sudo apt-get update
      - uses: ./.github/actions/set-up-kvm-for-e2e-tests
      - run: make -C test/e2e setup KUBERNETES_VERSION=${{ matrix.kubernetes-version }}
      - run: make -C test/e2e test KUBERNETES_VERSION=${{ matrix.kubernetes-version }}
