name: "e2e"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "LICENSE"
      - "NOTICE"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
      - "LICENSE"
      - "NOTICE"
    branches:
      - "main"
permissions:
  contents: read
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - 1.35.1
          - 1.34.4
    runs-on: "ubuntu-22.04"
    timeout-minutes: 60
    steps:
      - name: Check the disk information
        run: lsblk
      - name: Disk cleanup
        run: |
          # These code are copied from the following code:
          # https://github.com/shiguredo-webrtc-build/webrtc-build/blob/5a821e430b496bbff74cf45bab058ab4ac340c2c/.github/workflows/build.yml#L138-L147
          #    LICENSE: http://www.apache.org/licenses/LICENSE-2.0
          #    Copyright 2019-2025, Shiguredo Inc.
          df -h
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          df -h
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
      - run: sudo apt-get update
      - uses: ./.github/actions/set-up-kvm-for-e2e-tests
      - run: make -C test/e2e setup KUBERNETES_VERSION=${{ matrix.kubernetes-version }}
      - run: make -C test/e2e test KUBERNETES_VERSION=${{ matrix.kubernetes-version }}
